language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
  fast_finish: true

sudo: false


before_script:
  - composer self-update
  - composer update

script:
  - composer check

